### ISSUE TITLE
Constraints in grammar

### ISSUE THREAD

**Issue by groupsvkg** [petitparser/dart-petitparser#112]
Hello,

Is it possible to put constraints in grammar.

For example, if I want two values to be equal in different part of grammar.

**Comment by renggli** [comment]
Probably the simplest is to just throw an exception, which is what is done in the XML library: https://github.com/renggli/dart-xml/blob/5ebbd5c06e801c560fbb8d514bad18d8c5c763d6/lib/src/xml/grammar.dart#L105. This however does not work if your parser might want to continue with other choices.

A solution that makes this possible is to use a continuation parser:

```dart
final parser = digit() & digit().callCC((continuation, context) {
      final result = continuation(context);
      if (result.value[0] == result.value[1]) {
        return result;
      } else {
        return context.failure('values do not match');
      }
    });
```

The above parser parses two numbers, and only returns the successful parse result if they match. Otherwise a parse failure is created at the beginning of the expression. This could potentially be extracted to some reusable function where the predicate and the error message are specified?

Another way is to build the parser on the fly, as described here: https://stackoverflow.com/questions/64670722/parsing-delimited-strings-using-petitparser

**Comment by renggli** [comment]
With ebc81dc you can write:

```dart
final inner = digit() & digit();
final parser = inner.filter(
    (value) => result.value[0] == result.value[1], 
    'digits do not match');
```

**Comment by renggli** [comment]
With ebc81dc and 7cc80dc you can write:

```dart
final inner = digit() & digit();
final parser = inner.where(
    (value) => result.value[0] == result.value[1], 
    'digits do not match');
```
