### ISSUE TITLE
Labeled parsers to improve trace readability

### ISSUE THREAD

**Issue by shyndman** [petitparser/dart-petitparser#87]
While debugging this morning, I was thinking that it would be really handy to be able to introduce labeled parsers at important points in my grammar to make it easier to read through traces. These labeled parsers would defer to their children for their parsing needs, but when traced would display their label.

I'm going to write this myself, but just thought I'd put it out there.

Thanks!

**Comment by renggli** [comment]
Agreed, that would be a useful feature. The original implementation of PetitParser in Smalltalk had labels. They were auto-populated from the method names of the parser definitions, unfortunately I don't see an easy way to do this in Dart.

**Comment by shyndman** [comment]
`StackTrace.current` is the only thing I can think of, which is hacky obviously. But might be alright in a tracing scenario.

**Comment by shyndman** [comment]
I'm doing something similar with `StackTrace.current` here: https://github.com/mobxjs/mobx.dart/blob/master/flutter_mobx/lib/src/observer.dart#L53

**Comment by renggli** [comment]
I added labeled parsers and support in the debug tools with the latest commits. Unfortunately, the auto-labeling of productions remains tricky, because [method references](https://github.com/petitparser/dart-petitparser/blob/f561023b2fc8fde777b3f480f73e99cdffcd4492/petitparser/lib/src/definition/reference.dart#L40) generally don't have a readable `toString()` representation. I don't see how I can use `StackTrace.current`, because the method under question is not in the execution stack at the time I need the label.

So for now it means that productions have to be labeled manually, unless you have any other ideas how to infer some meaningful names automatically?

**Comment by renggli** [comment]
I am closing this as it was addressed by 0227dfe, b722dfd and 96073c8; and there are no new comments.
